services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: env.docker
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

  drupal:
    image: nrfc/www
    ports:
        - "9900:80"
    volumes:
      - files:/opt/drupal/web/sites/default/files
    env_file: env.docker
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  db-data:
  files:

# version: '3'
#
# services:
#   nginx-proxy:
#     image: jwilder/nginx-proxy
#     restart: always
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - certs:/etc/nginx/certs:ro
#       - vhostd:/etc/nginx/vhost.d
#       - html:/usr/share/nginx/html
#       - acme:/etc/acme.sh
#     labels:
#       - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
#
#   letsencrypt:
#     image: jrcs/letsencrypt-nginx-proxy-companion
#     restart: always
#     environment:
#       - NGINX_PROXY_CONTAINER=nginx-proxy
#     volumes:
#       - certs:/etc/nginx/certs:rw
#       - vhostd:/etc/nginx/vhost.d
#       - html:/usr/share/nginx/html
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - acme:/etc/acme.sh
#
#   www:
#     image: nginx
#     restart: always
#     expose:
#       - "80"
#     volumes:
#       - /Users/kbs/git/peladonerd/varios/1/www:/usr/share/nginx/html:ro
#     environment:
#       - VIRTUAL_HOST=pablokbs.com,www.pablokbs.com
#       - LETSENCRYPT_HOST=pablokbs.com,www.pablokbs.com
#       - LETSENCRYPT_EMAIL=pablo@pablokbs.com
#     depends_on:
#       - nginx-proxy
#       - letsencrypt
# volumes:
#   certs:
#   html:
#   vhostd:
#   acme: