services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d

  nginx:
    image: nginx
    ports:
      - 9900:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - drupal
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  drupal:
    image: nrfc/www
    build: .
    volumes:
      - /opt/drupal/web/modules
      - /opt/drupal/web/profiles
      - /opt/drupal/web/sites
      - /opt/drupal/web/themes
    env_file: .env.docker
    restart: unless-stopped

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_SMTP_PORT:-1025}:1025"
      - "${MAILER_ADMIN_PORT:-1080}:1080"

volumes:
  db-data:
